# Generated by Django 5.1.6 on 2025-03-20 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='piedra',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='piedras'),
        ),
    ]
