# Generated by Django 5.1.6 on 2025-03-20 19:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_piedra_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='piedra',
            name='fecha',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
