# Generated by Django 5.1.6 on 2025-03-20 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_piedra_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='piedra',
            name='fecha',
        ),
    ]
